#!/usr/bin/env bash
# Stop hook: write plans/session-handoff.md for the next session
# Fires when Claude finishes a turn (approximates session end)
#
# Guard: only rewrites handoff when content has meaningfully changed since
# the last write, preventing redundant overwrites on every single turn.

set -euo pipefail
trap 'echo "HOOK CRASH (session-end.sh line $LINENO): $BASH_COMMAND" >&2; exit 0' ERR

# Restore tmux window name on session end
"$HOME/.dotfiles/tmux/scripts/claude-tmux-bridge.sh" activity-stop >/dev/null 2>&1 || true

CWD=$(pwd)
TIMESTAMP=$(date '+%Y-%m-%d %H:%M')
HANDOFF="$CWD/plans/session-handoff.md"

# Only write if plans/ directory exists (opt-in per project)
[[ -d "$CWD/plans" ]] || exit 0

# Read artifact files
ACTIVE_CTX=""
[[ -f "$CWD/plans/active-context.md" ]] && ACTIVE_CTX=$(cat "$CWD/plans/active-context.md")

PROGRESS=""
[[ -f "$CWD/plans/progress.md" ]] && PROGRESS=$(cat "$CWD/plans/progress.md")

# --- Change-guard: skip write if artifact content hasn't changed since last handoff ---
CONTENT_HASH=$(printf '%s\n%s' "$ACTIVE_CTX" "$PROGRESS" | md5 2>/dev/null || printf '%s\n%s' "$ACTIVE_CTX" "$PROGRESS" | md5sum 2>/dev/null | cut -d' ' -f1)
HASH_FILE="/tmp/.claude-handoff-hash-$(id -u)-$(echo "$CWD" | md5 2>/dev/null || echo "$CWD" | md5sum 2>/dev/null | cut -d' ' -f1)"
if [[ -f "$HASH_FILE" ]] && [[ "$(cat "$HASH_FILE")" == "$CONTENT_HASH" ]] && [[ -f "$HANDOFF" ]]; then
    exit 0  # Content unchanged since last write — skip
fi

# Recent git commit
RECENT_COMMIT=$(git -C "$CWD" log -1 --oneline 2>/dev/null || echo "")
GIT_BRANCH=$(git -C "$CWD" branch --show-current 2>/dev/null || echo "")
GIT_STATE=$(git -C "$CWD" status --short 2>/dev/null | head -5 | tr '\n' '; ' | sed 's/; $//' || true)

# Seed skeleton files if ALL THREE artifact files are absent (so next session sees "stale" not "missing")
if [[ ! -f "$CWD/plans/active-context.md" ]] && \
   [[ ! -f "$CWD/plans/decisions.md" ]] && \
   [[ ! -f "$CWD/plans/progress.md" ]]; then
    python3 - "$CWD" <<'SKELEOF' || true
import sys, os
base = sys.argv[1] + "/plans"
skeletons = {
    "active-context.md": "# Active Context\n<!-- SKELETON — Claude: update with current session focus (≤30 lines per CLAUDE.md) -->\n",
    "decisions.md":      "# Decisions\n<!-- SKELETON — Claude: append ADL entries as architectural decisions are made -->\n",
    "progress.md":       "# Progress\n<!-- SKELETON — Claude: update task state using checkbox format per CLAUDE.md -->\n",
}
for fname, content in skeletons.items():
    path = os.path.join(base, fname)
    if not os.path.exists(path):
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
SKELEOF
fi

# Skip writing handoff if nothing meaningful to record
if [[ -z "$ACTIVE_CTX" ]] && [[ -z "$PROGRESS" ]]; then
    exit 0
fi

# Skip if content is skeleton-only (generated by this script's seed step)
is_skeleton() {
    local content="$1"
    # Strip lines that are: empty, headings, or SKELETON comment markers
    local stripped
    stripped=$(echo "$content" | grep -v '^[[:space:]]*$' | grep -v '^#' | grep -v '<!-- SKELETON')
    [[ -z "$stripped" ]]
}
if is_skeleton "$ACTIVE_CTX" && is_skeleton "$PROGRESS"; then
    exit 0
fi

python3 - "$TIMESTAMP" "$GIT_BRANCH" "$GIT_STATE" "$RECENT_COMMIT" \
    "$ACTIVE_CTX" "$PROGRESS" "$HANDOFF" <<'PYEOF'
import sys

(timestamp, branch, git_state, recent_commit,
 active_ctx, progress, handoff_path) = sys.argv[1:8]

lines = [
    f'# Session Handoff — {timestamp}',
    'status: pending',
    '',
    f'**Branch:** {branch}' if branch else '',
    f'**Uncommitted:** {git_state}' if git_state else '',
    f'**Last commit:** {recent_commit}' if recent_commit else '',
]
lines = [l for l in lines if l is not None]

if active_ctx:
    lines.append('')
    lines.append('## Active Context')
    lines.append(active_ctx)

if progress:
    lines.append('')
    lines.append('## Task State')
    lines.append(progress)

lines.append('')
lines.append('---')
lines.append('*Written by session-end.sh hook. Delete when no longer relevant.*')

with open(handoff_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
PYEOF

# Record content hash so next turn can skip if unchanged
echo "$CONTENT_HASH" > "$HASH_FILE"

# Inject /findings reminder to persist session discoveries to Serena memories
if [[ -f "$HANDOFF" ]]; then
    cat <<'REMINDER_EOF' >> "$HANDOFF"

---

## Session Insights Checkpoint

Before moving to the next task, consider running `/findings` to persist any architectural discoveries from this session to Serena memories. This keeps project knowledge durable across sessions instead of re-discovering patterns later.

**Session findings to capture:**
- Review `plans/decisions.md` — any new architectural decisions made today?
- Check `plans/active-context.md` — any insights about the domain or codebase structure?
- Identify non-obvious patterns, gotchas, or conventions worth preserving in project memories

Run `/findings` to guide this process.
REMINDER_EOF
fi

# Flush hook metrics to SQLite
"${BASH_SOURCE[0]%/*}/hook-metrics.sh" flush >/dev/null 2>&1 || true

# Clean up session-duration-guard counter
rm -f "/tmp/.claude-turn-count-${UID}" 2>/dev/null || true

exit 0
